### ISSUE TITLE
ModuleNotFoundError: No module named 'cassiopeia_diskstore'

### ISSUE THREAD

**Issue by Mee1ad** [zbee/mobahinted#1]
cassiopeia_diskstore is installed but after running main.exe getting this error

USING: Kernel with key (zbee's servers)
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import hinter.ui.main
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "hinter\__init__.py", line 49, in <module>
    cassiopeia.apply_settings(cassiopeia_settings)
  File "cassiopeia\cassiopeia.py", line 33, in apply_settings
  File "cassiopeia\_configuration\settings.py", line 159, in pipeline
  File "cassiopeia\_configuration\settings.py", line 29, in create_pipeline
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'cassiopeia_diskstore'
[8372] Failed to execute script main

**Comment by zbee** [comment]
To address the module not found issue, I see that pyinstaller was not properly packaging everything in the executable, as its module-finding is ... loosey-goosey. I addressed this in the commit that closed this issue, if you want to pull the latest code.

---

Additionally, I'm waiting for a release of Cassiopeia that includes my accepted pull request that patches an image with rune trees (meraki-analytics/cassiopeia/pull/369).
To address this issue yourself, until that release is ... released, you can monkey patch `mobahinted/venv/Lib/site-packages/cassiopeia/core/staticdata/rune.py` with the following  around line 70 (replace the current `image_url` property with the following code):

```
    @property
    def image_url(self):
        url = "https://ddragon.leagueoflegends.com/cdn/img/" + self._data[RunePathData].icon
        return url

    @lazy_property
    def image(self) -> PILImage:
        return configuration.settings.pipeline.get(PILImage, query={"url": self.image_url})
```

Finally, to address Kernel usage - I need to re-implement mhk-api.zbee.dev after moving hosting providers. Given that, to see the current status of the application you would need to generate a development API key to use via [developer.rito](https://developer.riotgames.com/) - once you have the key, you can create an `.env` file with the variable as described in the readme.
